name: plum

services:

  reverse-proxy:
    tty: true
    image: nginx:latest
    container_name: plum-reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/chatbot.html:/trial-page/chatbot.html
      # - ./reverse-proxy/certificate/fullchain.pem:/etc/nginx/danilocatone.duckdns.org.crt
      # - ./reverse-proxy/certificate/privkey.pem:/etc/nginx/danilocatone.duckdns.org.key
    ports:
      - 80:80
      - 443:443
    networks:
      - default

  plum_backend:
    build: ./plum-backend
    tty: true
    container_name: plum-backend
    image: plum-backend:latest
    restart: unless-stopped
    env_file:
      - plum-backend/.env
    volumes:
      - ./plum-backend:/plum-backend
      - ./plum-backend-models:/root/.cache/huggingface/hub
    ports:
      - "$GRADIO_SERVER_PORT:$GRADIO_SERVER_PORT"
      - 11434:11434
    networks:
      - default

  plum_frontend:
    build:
      context: plum-frontend
      target: development
    container_name: plum-frontend
    image: plum-frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./plum-frontend:/app
      - plum_frontend_node_modules:/app/node_modules
    networks:
      - default

  plum_database:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    env_file:
      - plum-backend/.env
    ports:
      - "$QDRANT__SERVICE__HTTP_PORT:$QDRANT__SERVICE__HTTP_PORT"
      - "$QDRANT__SERVICE__HTTPS_PORT:$QDRANT__SERVICE__HTTPS_PORT"
    expose:
      - $QDRANT__SERVICE__HTTP_PORT
      - $QDRANT__SERVICE__HTTPS_PORT
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - default


  plum_postgres:
    container_name: postgres
    image: postgres:latest
    tty: true
    env_file:
      - ./.env
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_SERVER=${POSTGRES_SERVER}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - default

  plum_pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    tty: true
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - SCRIPT_NAME=/pgadmin
    #   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    #   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - default

volumes:
  plum_frontend_node_modules:

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  default:
    driver: bridge
